name: vm_translator
description: A command-line application to translate VM code into the Hack assembly language.
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
